import Head from 'next/head'
import Image from 'next/image'
import Footer from '../components/Footer'


export default function Home() {
  return (
    <div >
      <Head>
        <title>Chapters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main  >
      
        <div className='flex justify-center mt-3'>

        <Image src='/navlogo.png' alt='logo' width={200} height={120} ></Image>
        </div>

          <h1 className='text-center font-bold text-4xl mb-3 '>
            Welcome to CHAPTERS
          </h1>
        <Image src='/home-pg.jpg' alt='background picture' width={1800} height={1500}className='my-10'></Image>

     

       

        
      </main>
      <Footer />

    </div>
  )
}
